# Generated by Django 3.2.7 on 2022-08-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20210916_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=150, null=True, verbose_name='Descripcion'),
        ),
    ]
